version: "3.8"

services:
  workspace-list-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/workspacedb
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - JWT_SECRET=clave_secreta
    depends_on:
      - db
      - cache

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workspacedb
    ports:
      - "5432:5432"

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
